---
# This is a basic workflow to help you get started with Actions

name: CI

env:
  GO_VERSION: "1.14.4"
  GOLANGCI_LINT_VERSION: "v1.28"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:

  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Install and run YAML Linter
  yamllint:
    name: YAML Lint
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install YAML Linter
      run: pip3 install --user yamllint

    - name: Run YAML Linter
      run: pip3 install --user yamllint

  golangci-lint:
    name: GolangCI Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
        # Required: the version of golangci-lint is required and must be specified without patch version:
        # we always use the latest patch version.
        version: ${{ env.GOLANGCI_LINT_VERSION }}

        # Optional: working directory, useful for monorepos
        # working-directory: somedir

        # Optional: golangci-lint command line arguments.
        # args: --issues-exit-code=0

        # Optional: show only new issues if it's a pull request. The default value is `false`.
        # only-new-issues: true

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.0
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: ${{ env.GO_VERSION }}

    - name: Build App
      run: go build .

  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # This job depends on the build job
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.0
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: ${{ env.GO_VERSION }}

    - name: Run Go tests
      run: go test ./...
...
